
steps:
- id: 'terraform init'
  name: 'hashicorp/terraform:1.0.0'
  dir: 'terraform'
  script: terraform init
- id: 'terraform plan'
  name: 'hashicorp/terraform:1.0.0'
  dir: 'terraform'
  script: terraform plan
- id: 'terraform apply'
  name: 'hashicorp/terraform:1.0.0'
  dir: 'terraform'
  script: terraform apply --var-file="environments/${ENVIRONMENT}.tfvars" --auto-approve