
steps:
- id: docker build and push
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-east1-docker.pkg.dev/liatrio-automation/node-repo/liatrio-takehome','--build-arg','ENVIRONMENT=${_ENVIRONMENT}','.' ]
- name: "gcr.io/cloud-builders/docker"
  args: ['push', 'us-east1-docker.pkg.dev/liatrio-automation/node-repo/liatrio-takehome']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  dir: 'src/manifest'
  args:
  - '-c'
  - |
    cp deployment.yaml temp.yaml
    sed -i "s/ENVIRONMENT/${_ENVIRONMENT}/g" temp.yaml deployment.yaml
    rm -f temp.yaml
- name: 'gcr.io/cloud-builders/kubectl'
  dir: 'src/manifest'
  args: ['apply', '-f', 'deployment.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=liatrio-test-cluster'