
steps:
- id: docker build and push
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-east1-docker.pkg.dev/liatrio-takehome1/node-repo/liatrio-takehome','--build-arg','ENVIRONMENT=${ENVIRONMENT}' '.' ]
- name: "gcr.io/cloud-builders/docker"
  args: ['push', 'us-east1-docker.pkg.dev/liatrio-takehome1/node-repo/liatrio-takehome']